### ISSUE TITLE
Possible missing parameter in CONTRIBUTING.rst?

### ISSUE THREAD

**Issue by OceanNuclear** [bielsnohr/scientific-python-cookiecutter#1]
The following line is written as
 `git clone git@{{ cookiecutter.vcs_domain }}:your_name_here/{{ cookiecutter.repo_name }}.git`
 rather than 
 `git clone git@{{ cookiecutter.vcs_domain }}:{{ cookiecutter.vcs_username }}/{{ cookiecutter.repo_name }}.git`

https://github.com/ukaea/scientific-python-cookiecutter/blob/a6607b0be445513b986d61f52cd65efed48c510e/%7B%7B%20cookiecutter.repo_name%20%7D%7D/CONTRIBUTING.rst#L62

Is that intentional?

**Comment by bielsnohr** [comment]
Thanks so much for looking through this!

It is indeed intentional. This particular section is giving instructions to an _arbitrary contributor_ about how to fork the repo and then pull it down. This isn't an instruction for the original developer using the cookiecutter. I think I have that straight in my head, but please do say if you think I got it wrong. I'll close the issue for now unless I hear something back.
